[package]
name = "nft_swap"
version = "0.1.0"
edition = "2024"

[dependencies]
ic-cdk = "^0.15.0"
ic-cdk-macros = "^0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
